### ISSUE TITLE
Readme needs update on example section

### ISSUE THREAD

**Issue by xr1337** [theoriginalbit/PreviewView#1]
`PreviewView`  as demonstrated in Examples doesnt seem to work with latest HEAD.

## Expected

Examples on Readme should be `Preview` 

```
struct YourViewController_Previews: PreviewProvider {
    static var previews: some View {
        Preview(for: YourViewController())
            .edgesIgnoringSafeArea(.all)
            .previewDevice(PreviewDevice(rawValue: "iPhone 11"))
    }
}
```

## Actual

Readme uses `PreviewView` in examples

```
struct YourViewController_Previews: PreviewProvider {
    static var previews: some View {
        Preview(for: YourViewController())
            .edgesIgnoringSafeArea(.all)
            .previewDevice(PreviewDevice(rawValue: "iPhone 11"))
    }
}
```

**Comment by theoriginalbit** [comment]
Thanks for bringing this back to my attention! I'll update the README shortly and also tag the latest commit in main since it's not actually available through SPM right now.

**Comment by theoriginalbit** [comment]
I've updated the README and tagged a new version; https://github.com/theoriginalbit/PreviewView/releases/tag/2.0.0

Later today I should be able to clean up and release some other changes I've had sitting around for a while, based on feedback from other developers on the rather janky API that this 2.0.0 version has when wrapping in a navigation controller.
