### ISSUE TITLE
Doesn't work in large app

### ISSUE THREAD

**Issue by linlinyao1** [theoriginalbit/PreviewView#2]
SwiftUIPreview render exceed 30 seconds and throw error when preview a custom view inside a large app (take over 10 mins to compile)

**Comment by theoriginalbit** [comment]
Yep! I thought I'd put a note the README in about that 🤔 

Unfortunately there's not much that can be done about it as it is a timeout enforced by Xcode. Though interesting that you're seeing a 30 second timeout, as the default is usually 5 seconds. You could try to break down the app into smaller components (frameworks) that can compiler faster, I've had more success with that, but unfortunately slow compile times will always give you mixed results.
