### ISSUE TITLE
Does not build for x86_64 simulator for porject which have to use x86_64 architecture for Simulator on Apple Silicone devices

### ISSUE THREAD

**Issue by roman-suvorov-onseo** [theoriginalbit/PreviewView#4]
`Could not find module 'PreviewView' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator`

SPM builds for arm64 despite the project explicitly specifying arm64 as an excluded architecture for the Simulator.
Due to this, a project that depends on older libraries that have no simulator[arm64] support fails to link with this library.

A CocoaPods support would have solved this issue due to Cocoapods being able to support architecture exclusion

**Comment by theoriginalbit** [comment]
Hey there, apologies for the delay in getting back to you on this issue.

I won't be adding a CocoaPods definition any time soon, you're welcome to make a PR if you wish.

In reality you should be avoiding excluding arm64 architecture from your project. All devices at this point are arm64 and Xcode offers Rosetta simulator destinations in those circumstances where you have dependencies that are precompiled frameworks that don't include simulator symbols.
